export const headContainer: string;
export const headerInner: string;
export const title: string;
export const dropdownMenu: string;
export const user: string;
export const headerTabs: string;
export const tabItem: string;
export const tabLink: string;
export const active: string;
